selfTest.obj: ..\jsapi.h
selfTest.obj: ..\jsprvtd.h
selfTest.obj: ..\jsvector.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
selfTest.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
