testUTF8.obj: ..\jsapi.h
testUTF8.obj: ..\jsprvtd.h
testUTF8.obj: ..\jsvector.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testUTF8.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
