testNewObject.obj: ..\jsapi.h
testNewObject.obj: ..\jsprvtd.h
testNewObject.obj: ..\jsvector.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testNewObject.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
