testTrap.obj: ..\jsapi.h
testTrap.obj: ..\jsdbgapi.h
testTrap.obj: ..\jsprvtd.h
testTrap.obj: ..\jsvector.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.tbl
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstdint.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsvalue.h
testTrap.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
