testDeepFreeze.obj: ..\jsapi.h
testDeepFreeze.obj: ..\jsprvtd.h
testDeepFreeze.obj: ..\jsvector.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testDeepFreeze.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
