testClassGetter.obj: ..\jsapi.h
testClassGetter.obj: ..\jsprvtd.h
testClassGetter.obj: ..\jsvector.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testClassGetter.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
