tests.obj: ..\jsapi.h
tests.obj: ..\jsprvtd.h
tests.obj: ..\jsvector.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
tests.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
