testOps.obj: ..\jsapi.h
testOps.obj: ..\jsprvtd.h
testOps.obj: ..\jsvector.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testOps.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
