testPropCache.obj: ..\jsapi.h
testPropCache.obj: ..\jsprvtd.h
testPropCache.obj: ..\jsvector.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testPropCache.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
