testGCChunkAlloc.obj: ..\jsapi.h
testGCChunkAlloc.obj: ..\jscntxt.h
testGCChunkAlloc.obj: ..\jsgcchunk.h
testGCChunkAlloc.obj: ..\jsprvtd.h
testGCChunkAlloc.obj: ..\jsvector.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js.msg
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsarena.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsarray.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsatom.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscell.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsclist.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsdbgapi.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsdhash.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsdtoa.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsfun.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsgc.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsgcchunk.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsgcstats.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jshash.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jshashtable.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinterp.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslock.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsmath.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsobj.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.tbl
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspropertycache.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspropertytree.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsscript.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstdint.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstr.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsvalue.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsvector.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
testGCChunkAlloc.obj: c:\projects\jet.framework.rc5\3dparty\js\src\prmjtime.h
