testXDR.obj: ..\jsapi.h
testXDR.obj: ..\jsprvtd.h
testXDR.obj: ..\jsscript.h
testXDR.obj: ..\jsvector.h
testXDR.obj: ..\jsxdrapi.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\js-config.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\../js-confdefs.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi-tests\tests.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsapi.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsatom.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsbit.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscell.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsclist.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscompat.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jscpucfg.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsdbgapi.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jshash.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jshashtable.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsinttypes.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslock.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jslong.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsobj.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsopcode.tbl
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsotypes.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsproto.tbl
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsprvtd.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jspubtd.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstaticcheck.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstdint.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsstr.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstl.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jstypes.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsutil.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsval.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsvalue.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsvector.h
testXDR.obj: c:\projects\jet.framework.rc5\3dparty\js\src\jsversion.h
